Feature/eid login
slovensko-digital/navody.digital pull request #656
Opened 2024-04-26 16:58 UTC by cizmarty

2024-04-27 15:06 UTC, jsuchal commented on app/views/sessions/insufficient_representation.html.erb
> +    <p class="govuk-body-lead">Nemáte dostatočné oprávnenia aby ste mohli reprezentovať zvolený subjekt.</p>
```suggestion
    <p class="govuk-body-lead">Nemáte dostatočné oprávnenia, aby ste mohli zastupovať zvolený subjekt.</p>
```

2024-04-27 15:07 UTC, jsuchal commented on db/migrate/20240427124856_add_subject_data_to_users.rb
> +    add_index :users, :subject_edesk_number
Toto asi netreba

2024-04-27 15:08 UTC, jsuchal requested changes
nejake mini zmeny a mozeme. Test na toto je asi problem spravit ci?

2024-04-27 16:40 UTC, jsuchal commented on app/models/upvs/assertion.rb
> +    def self.assertion(eid_token, client: Faraday, url: "#{ENV.fetch('AUTH_EID_BASE_URL')}/api/upvs/assertion?token=#{eid_token&.api_token}")
@celuchmarek @luciajanikova toto potrebujeme pridat na prod aj staging.

2024-04-29 13:30 UTC, jsuchal commented
@luciajanikova @celuchmarek toto je ready na merge, ale potrebujeme nastavit ENVs.

2024-04-29 16:08 UTC, celuchmarek commented
@jsuchal nahodil som env

2024-04-30 12:09 UTC, jsuchal approved these changes

2024-04-30 12:13 UTC, merged